### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by Roboxkin** [lonely-code-cube/cloudfire#1]
F:\CloudFail>main.py
Traceback (most recent call last):
  File "F:\CloudFail\main.py", line 7, in <module>
    from core import cookies
  File "F:\CloudFail\core\cookies.py", line 4, in <module>
    from aioredis import Redis
  File "C:\Users\Javascript\AppData\Roaming\Python\Python311\site-packages\aioredis\__init__.py", line 1, in <module>
    from aioredis.client import Redis, StrictRedis
  File "C:\Users\Javascript\AppData\Roaming\Python\Python311\site-packages\aioredis\client.py", line 32, in <module>
    from aioredis.connection import (
  File "C:\Users\Javascript\AppData\Roaming\Python\Python311\site-packages\aioredis\connection.py", line 33, in <module>
    from .exceptions import (
  File "C:\Users\Javascript\AppData\Roaming\Python\Python311\site-packages\aioredis\exceptions.py", line 14, in <module>
    class TimeoutError(asyncio.TimeoutError, builtins.TimeoutError, RedisError):
TypeError: duplicate base class TimeoutError

F:\CloudFail>uvicorn main:app
"uvicorn" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

F:\CloudFail>main:app
Синтаксическая ошибка в имени файла, имени папки или метке тома.

**Comment by libmid** [comment]
> F:\CloudFail>main.py
Traceback (most recent call last):
File "F:\CloudFail\main.py", line 7, in
from core import cookies
File "F:\CloudFail\core\cookies.py", line 4, in
from aioredis import Redis
File "C:\Users\Javascript\AppData\Roaming\Python\Python311\site-packages\aioredis_init_.py", line 1, in
from aioredis.client import Redis, StrictRedis
File "C:\Users\Javascript\AppData\Roaming\Python\Python311\site-packages\aioredis\client.py", line 32, in
from aioredis.connection import (
File "C:\Users\Javascript\AppData\Roaming\Python\Python311\site-packages\aioredis\connection.py", line 33, in
from .exceptions import (
File "C:\Users\Javascript\AppData\Roaming\Python\Python311\site-packages\aioredis\exceptions.py", line 14, in
class TimeoutError(asyncio.TimeoutError, builtins.TimeoutError, RedisError):
TypeError: duplicate base class TimeoutError

This should be fixed now

>"uvicorn" не является внутренней или внешней
командой, исполняемой программой или пакетным файлом.

Looks like you dont have uvicorn installed for some reason. Install it (with `pip install uvicorn`) and try again

**Comment by Roboxkin** [comment]
Thank you very much for the answer! I installed everything as you suggested, no errors, but nothing starts
